### ISSUE TITLE
Footstep Error?

### ISSUE THREAD

**Issue by Odorousbag87** [mmaulwurff/hellscape-navigator#25]
Called from m8f_hn_FootstepHandler.makeFoostepMarks at Hellscape Navigator (any version).pk3: zscript/m8f_hn_footsteps.zs, line 105
Called from m8f_hn_FootstepHandler.makeFoostepMarks.WorldTick at hellscape-navigator-(any version).pk3:zscript/m8f_hn_footsteps.zs, line 92

Not sure if this mod is still being worked on but I get these errors in any version of GZDoom (even the recent one). This is with any version of navigator including 0.15. It's the same error and the only difference is the version info in the file name. But this happens in the console when I go to start the game. I have removed all mods but this one. I have tried loading Doom 2 or any IWAD. Is there a setting I am missing or I feel like that this is user error.

**Comment by mmaulwurff** [comment]
@Odorousbag87, you haven't posted the error itself, only where it happens. Is it `VM execution aborted: division by zero.` or something else?

Anyway, can you please check your `m8f_hn_marker_spawn_period` CVar value?

**Comment by Odorousbag87** [comment]
The error is VM execution aborted: division by zero. 

Sure I will check that now.

**Comment by Odorousbag87** [comment]
That value is 0

**Comment by mmaulwurff** [comment]
Option menu doesn't allow to set it to zero. Did you set it manually, from console?

Set it to anything above zero, and the error won't happen anymore.

**Comment by Odorousbag87** [comment]
Okay sweet thank you!
